cloudEvents:
  address: :40000
  shutdownTimeout: 10s

gRPC:
  address: :50051
  log:
    level: debug
    output: file
    file:
      name: ./grpc-server
      extensionName: log
      addDate: false
    withCallerInfo: true

http:
  echo:
    address: :10000
  gin:
    address: :10001
  mux:
    address: :10002
  swaggerAddress: 127.0.0.1:10000
  swaggerUri: /swagger/
  shutdownTimeout: 10s
  log:
    level: debug
    output: file
    file:
      name: ./http-server
      extensionName: log
      addDate: false
    withCallerInfo: true

longPolling:
  address: :30000
  timeoutSeconds: 3600
  shutdownTimeout: 10s
  subscriptionURI: /subscription
  publishURI: /publish
  filePersistorInfo:
      use: false
      fileName: ./file-persistor.txt
      writeBufferSize: 250
      writeFlushPeriodSeconds: 1
  log:
    level: debug
    output: file
    file:
      name: ./long-polling-server
      extensionName: log
      addDate: false
    withCallerInfo: true

socket:
  tcp:
    address: :20000
  udp:
    address: :20001
  clientPoolSize: 1024
  log:
    level: debug
    output: file
    file:
      name: ./socket-server
      extensionName: log
      addDate: false
    withCallerInfo: true
